In [5]:
import numpy as np
import torch
from torch import nn

In [4]:
np.tile(np.array(range(5)), [5, 1])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [14]:
>>> m = nn.Conv1d(15, 43, 3w stride=2)
>>> input = torch.randn(20, 15, 50)
>>> output = m(input)
output.shape

torch.Size([20, 43, 24])

In [15]:
>>> m = nn.Conv2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2), dilation=(3, 1))
>>> input = torch.randn(20, 16, 50, 100)
>>> output = m(input)
output.shape

torch.Size([20, 33, 26, 100])

In [19]:
x = torch.arange(10).unsqueeze(1)
x

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [28]:
x.transpose(-1, -2)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])